### ISSUE TITLE
Custom selection style support

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/jekyll-theme-yat#119]
Add new feature for users to custom selection style with below options in `_config.yml`.

```yml
# You can custom selection style
selection:
   color: "#ff00ff"
   background_color: "yellow"
```
