### ISSUE TITLE
Rich excerpt with image support

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/jekyll-theme-yat#125]
Add multiple styles of excerpt images for users, so that their visitors can not only see the text excerpt of an article, but also the image. The configuration as below:

```yml
# Excerpt settings
excerpt:
  default_image: /assets/images/default-image.jpeg  # Default image when the image style is not none
  image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
  image_width: 38.2%      # Image default width
  image_height: 160px     # Image default height
  content_size: 350       # Words default size
```
