### ISSUE TITLE
Question: How can i customize the orange colored tags?

### ISSUE THREAD

**Issue by CypherpunkSamurai** [jeffreytse/jekyll-theme-yat#41]
Hi,
I want to customize the orange color in titles and tags. Can you please tell me how i can do it?

**Comment by jeffreytse** [comment]
Hi @CypherpunkSamurai 

Thanks for your patience, the latest commit (c5212c60ad8058732c17b3107ffd1b6a05850bd4) has supported to customize the brand color. There is an option called `brand_color` in `_config.yml` for you to do it.

```yml
# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
brand_color: orangered

# Custom color as below:
brand_color: "#1a8e42"
```

Also, there is another powerful plugin called [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship), I developped it and welcome to have a glance.

Thanks and regards
