### ISSUE TITLE
Is there a way to override CSS without unpacking the gem?

### ISSUE THREAD

**Issue by dogweather** [jeffreytse/jekyll-theme-yat#98]
I'd like to override just the font size. In development, I'm trying this in `assets/main.scss`:

```css
---
---
@import "{{ site.theme }}";

body {
    font-size: 16px;
}
```

But I get the error:

```
Error: File to import not found or unreadable: jekyll-theme-yat. (SassC::SyntaxError)
```
